name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted  # Local machine pe run hoga

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get runner number
        id: runner_number
        run: echo "RUNNER_NUMBER=${{ github.run_id }}" >> $GITHUB_ENV  

      - name: Display runner number
        run: echo "Runner Number: ${{ env.RUNNER_NUMBER }}"

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          echo "Building Docker image with tag: mohitgaur1272/gaur13:${{ env.RUNNER_NUMBER }}"
          docker build -t mohitgaur1272/gaur13:${{ env.RUNNER_NUMBER }} .

      - name: Push Docker image to Docker Hub
        run: docker push mohitgaur1272/gaur13:${{ env.RUNNER_NUMBER }}

      - name: Remove Local Docker Image (Free Up Space)
        run: docker rmi mohitgaur1272/gaur13:${{ env.RUNNER_NUMBER }} --force

      - name: Remove Unused Docker Data
        run: docker system prune -af

  trivy_scan:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Pull Docker image from Docker Hub
        run: docker pull mohitgaur1272/gaur13:${{ env.RUNNER_NUMBER }}

      - name: Run Trivy vulnerability scan
        run: trivy image --severity HIGH,CRITICAL mohitgaur1272/gaur13:${{ env.RUNNER_NUMBER }}

  run_container:
    runs-on: self-hosted
    needs: trivy_scan

    steps:
      - name: Run Docker container
        run: docker run -itd --name mohit -p 100:80 mohitgaur1272/gaur13:${{ env.RUNNER_NUMBER }}
