name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted  # Running on self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get runner number
        run: echo "RUNNER_NUMBER=${{ github.run_id }}" >> $GITHUB_ENV  

      - name: Display runner number
        run: echo "Runner Number:${{ env.RUNNER_NUMBER }}"

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          echo "Building Docker image with tag: mohitgaur1272/gaur13:${{ env.RUNNER_NUMBER }}"
          docker build -t mohitgaur1272/gaur13:${{ env.RUNNER_NUMBER }} .

      - name: Push Docker image to Docker Hub
        run: docker push mohitgaur1272/gaur13:${{ env.RUNNER_NUMBER }}

      - name: Remove Local Docker Image (Free Up Space)
        run: docker rmi mohitgaur1272/gaur13:${{ env.RUNNER_NUMBER }} --force

      - name: Remove Unused Docker Data
        run: docker system prune -af

  sonar_scan:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run SonarQube Analysis
        run: |
          /opt/sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=mohit \
            -Dsonar.sources=${{ github.workspace }} \
            -Dsonar.host.url=http://3.110.210.151:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  trivy_scan:
    runs-on: self-hosted
    needs: sonar_scan

    env:
      RUNNER_NUMBER: ${{ needs.build.outputs.RUNNER_NUMBER }}
 
    steps:
      - name: Debug RUNNER_NUMBER
        run: echo "Runner Number:${{ env.RUNNER_NUMBER }}"
        
      - name: Pull Docker image from Docker Hub
        run: docker pull mohitgaur1272/gaur13:${{ env.RUNNER_NUMBER }}

      - name: Scan Image with Trivy
        run: trivy image --severity HIGH,CRITICAL mohitgaur1272/gaur13:${{ env.RUNNER_NUMBER }}

  deploy:
    runs-on: self-hosted
    needs: trivy_scan

    #env:
    #  RUNNER_NUMBER: ${{ needs.build.outputs.RUNNER_NUMBER }}
      
    steps:
      - name: Run Docker container
        run: docker run -itd --name mohit -p 100:80 mohitgaur1272/gaur13:${{ env.RUNNER_NUMBER }}
